### ISSUE TITLE
Properly Dockerize

### ISSUE THREAD

**Issue by jaspermayone** [phish-directory/api#4]

**Comment by geekyharsh05** [comment]
@jaspermayone Can you please assign me?

**Comment by geekyharsh05** [comment]
@jaspermayone I'll suggest can we use bcryptjs instead of bcrypt?
issue: [click here](https://stackoverflow.com/questions/70852805/bcrypt-error-in-docker-container-error-path-to-local-module-node-modules-bcry)

**Comment by jaspermayone** [comment]
We can build bycrypt in, see https://stackoverflow.com/a/78997988

I would prefer to use the main package instead of changing packages.

**Comment by geekyharsh05** [comment]
@jaspermayone Yeah i figured that out. Thanks.

**Comment by geekyharsh05** [comment]
@jaspermayone Do you want both files? for prod and dev?

**Comment by jaspermayone** [comment]
Yes please!

**Comment by geekyharsh05** [comment]
@jaspermayone Thanks man!

**Comment by jaspermayone** [comment]
Ofc! Ty!
